#!/bin/sh /etc/rc.common
START=95
STOP=13
USE_PROCD=1
run_reboot()
{
	local enable
	config_get_bool enable $1 enable

	if [ $enable = 1 ]; then
		local minute
		local hour
		config_get week $1 week
		config_get minute $1 minute
		config_get hour $1 hour
		if [ $minute = 0 ] ; then
			minute="00"
		fi
		if [ $week = 7 ] ; then
			week="*"
		fi
		# 删除旧的 crontab 条目
		sed -i '/reboot/d' /etc/crontabs/root >/dev/null 2>&1
		# 添加新的 crontab 条目
		echo "$minute $hour * * $week sleep 5 && touch /etc/banner && reboot" >> /etc/crontabs/root
		# 重启 cron 服务
		/etc/init.d/cron restart
		echo "Auto REBOOT has started.">> /tmp/autoreboot.log
	else
		# 如果禁用，删除 crontab 条目并重启 cron
		sed -i '/reboot/d' /etc/crontabs/root >/dev/null 2>&1
		/etc/init.d/cron restart
	fi
}
service_triggers()
{
	procd_add_reload_trigger "autoreboot"
}

start_service()
{	
	config_load autoreboot
	config_foreach run_reboot login
}

stop_service()
{
	sed -i '/reboot/d' /etc/crontabs/root >/dev/null 2>&1
	/etc/init.d/cron restart
	echo "Auto REBOOT has stopped."
}

