#!/bin/bash

# 日志清理脚本 - 每小时删除指定目录中的.tar.gz日志文件
# 作者：Generated by AI
# 日期：2025-06-05

# 目标目录数组（可扩展添加更多目录）
TARGET_DIRS=(
    "/mnt/iot/logs"
    "/mnt/data_collect/logs"
)

# 日志保留天数（根据需求调整）
DAYS_TO_KEEP=0  # 0表示立即删除所有匹配文件

# 主清理函数
cleanup_old_logs() {
    for dir in "${TARGET_DIRS[@]}"; do
        # 检查目录是否存在
        if [ ! -d "$dir" ]; then
            echo "[WARNING] 目录不存在: $dir" >&2
            continue
        fi
        
        # 查找并删除.tar.gz文件
        find "$dir" -type f -name '*.tar.gz' -mtime +$DAYS_TO_KEEP -print -delete
    done
}

# 执行清理
echo "[$(date '+%Y-%m-%d %H:%M:%S')] 开始日志清理任务"
cleanup_old_logs
echo "[$(date '+%Y-%m-%d %H:%M:%S')] 日志清理任务完成"