#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/etc/init.d/plugin-monitor


start_service() {

    procd_open_instance
    procd_set_param command /bin/sh /etc/init.d/plugin-monitor.sh
    procd_set_param respawn
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    stop
    start
}

stop_service() {
    procd_open_instance
    procd_close_instance
} 