#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	sleep 10 # wait system network ok 

	echo "service data_collect start" >/tmp/data_collect.run

	procd_open_instance
	procd_set_param command data_collect
	procd_append_param command -config
	procd_append_param command /etc/data_collect/configs/conf.yml
	procd_set_param respawn
	procd_close_instance

}
