#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

# start_service 函数必须要重新定义
start_service() {
	echo service ser2mqtt start
    procd_open_instance
    procd_set_param command ser2mqtt # mycode执行的命令是 ser2mqtt
    procd_set_param respawn # 定义respawn参数，告知procd当mycode程序退出后尝试进行重启
    procd_close_instance  # 关闭实例
}