# See /LICENSE for more information.
# This is free software, licensed under the GNU General Public License v2.

include $(TOPDIR)/rules.mk


PKG_NAME:=luci-app-iotService
LUCI_TITLE:=LuCI support for Iot Service
LUCI_PKGARCH:=all
PKG_VERSION:=1.0.0
PKG_LICENSE:=GPLv3
PKG_LINCESE_FILES:=LICENSE
LUCI_DEPENDS:=+luci-compat +iot

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
